#!/usr/bin/env bash
# reflector.sh — Consolidates observations when they grow too large
# Triggered by observer when observations exceed WORD_THRESHOLD
#
# Environment variables:
#   OPENCLAW_DIR, WORKSPACE_DIR, OPENROUTER_API_KEY, OBSERVER_MODEL, OBSERVER_API_URL

set -eo pipefail

# Validate required env
if [[ -z "${OPENROUTER_API_KEY:-}" ]]; then
  echo "ERROR: OPENROUTER_API_KEY not set. Export it or add to .env" >&2
  exit 1
fi

WORKSPACE_DIR="${WORKSPACE_DIR:-$HOME/clawd}"
OBSERVATIONS_FILE="${WORKSPACE_DIR}/memory/observations.md"
BACKUP_DIR="${WORKSPACE_DIR}/memory/observation-backups"
LOG="${WORKSPACE_DIR}/logs/reflector.log"
WORD_THRESHOLD="${REFLECTOR_THRESHOLD:-8000}"

MODEL="${OBSERVER_MODEL:-google/gemini-2.0-flash-001}"
API_URL="${OBSERVER_API_URL:-https://openrouter.ai/api/v1/chat/completions}"

mkdir -p "$BACKUP_DIR" "$(dirname "$LOG")"
log() { echo "$(date '+%Y-%m-%d %H:%M:%S') $*" >> "$LOG"; }

# Check if reflection needed
WORDS=$(wc -w < "$OBSERVATIONS_FILE" 2>/dev/null || echo 0)
if [ "$WORDS" -lt "$WORD_THRESHOLD" ]; then
  exit 0
fi

log "Reflector triggered: $WORDS words (threshold: $WORD_THRESHOLD)"

# Backup current observations
BACKUP="${BACKUP_DIR}/observations-$(date '+%Y%m%d-%H%M%S').md"
cp "$OBSERVATIONS_FILE" "$BACKUP"
log "Backed up to $BACKUP"

# Load system prompt
SYSTEM_PROMPT="You are a reflection agent. Consolidate and compress observation logs.
Merge duplicate facts. Remove outdated entries (superseded by newer info).
Preserve all 🔴 high-priority items. Compress 🟡 medium items. Summarise 🟢 low items.
Keep the same format: dated sections with prioritised bullets.
Output must be SHORTER than input while preserving all important information."

if [ -f "${WORKSPACE_DIR}/prompts/reflector-system.txt" ]; then
  SYSTEM_PROMPT=$(cat "${WORKSPACE_DIR}/prompts/reflector-system.txt")
fi

CONTENT=$(cat "$OBSERVATIONS_FILE")
PAYLOAD=$(jq -n --arg sys "$SYSTEM_PROMPT" --arg content "$CONTENT" '{
  model: env.MODEL,
  messages: [
    {role: "system", content: $sys},
    {role: "user", content: ("Consolidate these observations:\n\n" + $content)}
  ],
  temperature: 0.2,
  max_tokens: 4000
}')

RESPONSE=$(curl -s -X POST "$API_URL" \
  -H "Authorization: Bearer ${OPENROUTER_API_KEY}" \
  -H "Content-Type: application/json" \
  -d "$PAYLOAD" 2>/dev/null)

REFLECTED=$(echo "$RESPONSE" | jq -r '.choices[0].message.content // empty' 2>/dev/null)

if [ -z "$REFLECTED" ]; then
  log "ERROR: No reflection output. Keeping original."
  exit 1
fi

# Sanity check: output should be shorter than input
NEW_WORDS=$(echo "$REFLECTED" | wc -w)
if [ "$NEW_WORDS" -gt "$WORDS" ]; then
  log "ERROR: Reflection ($NEW_WORDS words) is LARGER than input ($WORDS words). Keeping original."
  exit 1
fi

# Write reflected observations
echo "# Observations Log" > "$OBSERVATIONS_FILE"
echo "" >> "$OBSERVATIONS_FILE"
echo "Auto-generated by Observer agent. Loaded at session startup for cross-session memory." >> "$OBSERVATIONS_FILE"
echo "Last reflected: $(date '+%Y-%m-%d %H:%M')" >> "$OBSERVATIONS_FILE"
echo "" >> "$OBSERVATIONS_FILE"
echo "---" >> "$OBSERVATIONS_FILE"
echo "" >> "$OBSERVATIONS_FILE"
echo "$REFLECTED" >> "$OBSERVATIONS_FILE"

log "Reflection complete: $WORDS → $NEW_WORDS words ($(( (WORDS - NEW_WORDS) * 100 / WORDS ))% reduction)"
